FROM node:22.14.0-bullseye

# Install system dependencies and build tools
RUN set -e; \
    apt update; \
    apt install -y gettext git tzdata build-essential python3 make g++; \
    rm -rf /var/lib/apt/lists/*

ENV TZ=America/Edmonton
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG branch=master

ENV NODE_ENV=production
WORKDIR /opt/magic_mirror

# Clone MagicMirror repository
RUN git clone -b master https://github.com/MagicMirrorOrg/MagicMirror .

# Backup default modules and config
RUN cp -R modules /opt/default_modules
RUN cp -R config /opt/default_config

# Clean npm cache
RUN npm cache clean --force

# Install MagicMirror dependencies with verbose output for debugging
RUN npm install --unsafe-perm --verbose

# Clone MMM-CalendarExt3 module into the modules folder
RUN git clone https://github.com/MMRIZE/MMM-CalendarExt3.git /opt/magic_mirror/modules/MMM-CalendarExt3

# Install CalendarExt3 dependencies
WORKDIR /opt/magic_mirror/modules/MMM-CalendarExt3
RUN npm install --unsafe-perm --silent
RUN git submodule update --init --recursive

# Clone MMM-ImageSlideshow module into the modules folder
RUN git clone https://github.com/AdamMoses-GitHub/MMM-ImageSlideshow.git /opt/magic_mirror/modules/MMM-ImageSlideshow

# Expose the volumes for css, modules, and config
VOLUME [ "/opt/magic_mirror/css/", "/opt/magic_mirror/modules", "/opt/magic_mirror/config" ]

WORKDIR /opt/magic_mirror

COPY mm-docker-config.js docker-entrypoint.sh ./
RUN chmod +x ./docker-entrypoint.sh

EXPOSE 8282

ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["node", "serveronly"]
